name: Update Course Podcast
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install yt-dlp
        run: pip install yt-dlp
          
      - name: Generate RSS feed
        run: python scripts/podcast.py
          
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.rss
          git commit -m "Update podcast feed" || echo "No changes"
          git push
