name: Update Course Podcast
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yt-dlp

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main

      - name: Generate RSS feed
        run: python scripts/podcast_generator.py

      - name: Commit and push
        run: |
          git add feed.rss
          if ! git diff --staged --quiet; then
            git commit -m "Update podcast feed"
            git pull --rebase origin main
            git push origin main
            echo "✅ Changes pushed successfully"
          else
            echo "ℹ️ No changes to commit"
          fi
