name: Update Course Podcast
on:
  schedule:
    - cron: '0 */4 * * *'  # Alle 4 Stunden prüfen
  workflow_dispatch:  # Manuell auslösbar
  push:
    branches: [ main ]

jobs:
  update-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install yt-dlp podgen
          
      - name: Run podcast generator
        run: |
          python scripts/podcast_generator.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add feed.rss
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update podcast feed"
          git push
