name: Update Course Podcast
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-podcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install yt-dlp
          
      - name: Reset and regenerate
        run: |
          # Setze lokale Änderungen zurück
          git checkout HEAD -- feed.rss
          git pull origin main
          
      - name: Run podcast generator
        run: |
          python scripts/podcast_generator.py
          
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add feed.rss
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update podcast feed"
            git push origin main
          else
            echo "No changes to commit"
          fi
